# Pull node image
FROM node:16-alpine3.14

#specify and change workdir
WORKDIR '/app'

#copy package.json
COPY ./package.json .

#run npm install
RUN npm install

#copy the rest of files
COPY . .

#set the start up command the dev server -as i got-
CMD ["npm","run","start"]
