sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t doc20az/react-client-test -f ./client/Dockerfile.dev ./client

# run test on our react app
script:
  - docker run -e CI=true doc20az/react-client-test npm test

# after successful test ... building production images and push it to docker-hub 
after_success:  
  - docker build -t doc20az/multi-client ./client
  - docker build -t doc20az/multi-nginx ./nginx
  - docker build -t doc20az/multi-server ./server
  - docker build -t doc20az/multi-worker ./worker
  # in order to push your images to docker hub ... you have to login 
  # to yr account throw docker-cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  #push the images to docker hub
  - docker push doc20az/multi-client
  - docker push doc20az/multi-nginx
  - docker push doc20az/multi-server
  - docker push doc20az/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-containerized-app"
  env: "Multicontainerizedapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-712504446150"
  bucket_path: "multi-containerized-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY


