version: '3'
services:
  client:
    image: "doc20az/multi-client"
    mem_limit: 128m
    hostname: client
  backend:
    image: "doc20az/multi-server"
    mem_limit: 128m
    hostname: backend
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "doc20az/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment: 
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx_proxy:
    image: "doc20az/multi-nginx"
    mem_limit: 128m
    hostname: nginx_proxy
    ports:
      - "8090:80"